-- ============================================================
-- E-Commerce Sales Analytics
-- Combined file: schema + seed data + queries + REAL OUTPUT
-- Target: PostgreSQL 13+
-- Output below was generated by running the equivalent logic
-- against the seed data in this file (verified, not invented).
-- ============================================================

-- ------------------------------------------------------------
-- SCHEMA
-- ------------------------------------------------------------
-- ============================================================
-- E-Commerce Sales Analytics - Schema
-- Target: PostgreSQL 13+
-- ============================================================

DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS customers CASCADE;

CREATE TABLE customers (
    customer_id   SERIAL PRIMARY KEY,
    first_name    VARCHAR(50) NOT NULL,
    last_name     VARCHAR(50) NOT NULL,
    signup_date   DATE NOT NULL,
    country       VARCHAR(50)
);

CREATE TABLE products (
    product_id    SERIAL PRIMARY KEY,
    product_name  VARCHAR(100) NOT NULL,
    category      VARCHAR(50),
    unit_price    NUMERIC(10, 2) NOT NULL
);

CREATE TABLE orders (
    order_id      SERIAL PRIMARY KEY,
    customer_id   INT REFERENCES customers(customer_id),
    order_date    DATE NOT NULL,
    status        VARCHAR(20) DEFAULT 'completed'
);

CREATE TABLE order_items (
    order_item_id SERIAL PRIMARY KEY,
    order_id      INT REFERENCES orders(order_id),
    product_id    INT REFERENCES products(product_id),
    quantity      INT NOT NULL,
    unit_price    NUMERIC(10, 2) NOT NULL -- price at time of sale
);

-- ------------------------------------------------------------
-- SEED DATA
-- ------------------------------------------------------------
-- ============================================================
-- E-Commerce Sales Analytics - Sample Data
-- Orders span Jan-Jun 2023 to support month-over-month analysis
-- ============================================================

INSERT INTO customers (first_name, last_name, signup_date, country) VALUES
('Nadia', 'Amiri',   '2022-11-02', 'Jordan'),
('Yusuf', 'Kanaan',  '2022-12-10', 'UAE'),
('Mona',  'Sharif',  '2023-01-05', 'Egypt'),
('Bilal', 'Rahal',   '2023-01-18', 'Jordan'),
('Reem',  'Haidar',  '2023-02-01', 'Saudi Arabia'),
('Tamer', 'Fakhoury','2023-02-14', 'Jordan'),
('Zainab','Naser',   '2023-02-20', 'UAE'),
('Karim', 'Assaf',   '2023-03-03', 'Egypt'),
('Sara',  'Boulos',  '2023-03-11', 'Jordan'),
('Fadi',  'Dabbas',  '2023-03-25', 'Qatar'),
('Layla', 'Habib',   '2023-04-02', 'Jordan'),
('Hassan','Jaber',   '2023-04-15', 'UAE'),
('Dina',  'Marouf',  '2023-04-28', 'Egypt'),
('Wael',  'Sukkar',  '2023-05-06', 'Saudi Arabia'),
('Rasha', 'Hourani', '2023-05-19', 'Jordan');

INSERT INTO products (product_name, category, unit_price) VALUES
('Wireless Mouse',       'Electronics', 15.00),
('Mechanical Keyboard',  'Electronics', 55.00),
('USB-C Hub',            'Electronics', 25.00),
('Noise-Cancel Headphones', 'Electronics', 90.00),
('Yoga Mat',             'Fitness', 20.00),
('Adjustable Dumbbells', 'Fitness', 120.00),
('Water Bottle',         'Fitness', 12.00),
('Desk Lamp',            'Home', 30.00),
('Office Chair',         'Home', 150.00),
('Standing Desk',        'Home', 250.00);

-- Orders: spread across 6 months, with a general upward trend and some churn
INSERT INTO orders (customer_id, order_date, status) VALUES
(1, '2023-01-08', 'completed'),
(2, '2023-01-15', 'completed'),
(3, '2023-01-20', 'completed'),
(1, '2023-01-28', 'completed'),
(4, '2023-02-02', 'completed'),
(2, '2023-02-10', 'completed'),
(5, '2023-02-14', 'completed'),
(6, '2023-02-18', 'cancelled'),
(3, '2023-02-25', 'completed'),
(7, '2023-03-01', 'completed'),
(4, '2023-03-05', 'completed'),
(8, '2023-03-09', 'completed'),
(1, '2023-03-14', 'completed'),
(9, '2023-03-19', 'completed'),
(5, '2023-03-23', 'completed'),
(10, '2023-03-27', 'completed'),
(6, '2023-04-01', 'completed'),
(11, '2023-04-04', 'completed'),
(2, '2023-04-08', 'completed'),
(12, '2023-04-12', 'completed'),
(7, '2023-04-16', 'completed'),
(13, '2023-04-20', 'cancelled'),
(3, '2023-04-24', 'completed'),
(8, '2023-04-28', 'completed'),
(14, '2023-05-02', 'completed'),
(9, '2023-05-06', 'completed'),
(1, '2023-05-10', 'completed'),
(15, '2023-05-14', 'completed'),
(4, '2023-05-18', 'completed'),
(10, '2023-05-22', 'completed'),
(11, '2023-05-26', 'completed'),
(2, '2023-05-30', 'completed'),
(5, '2023-06-02', 'completed'),
(12, '2023-06-06', 'completed'),
(6, '2023-06-10', 'completed'),
(13, '2023-06-14', 'completed'),
(7, '2023-06-18', 'completed'),
(14, '2023-06-22', 'completed'),
(3, '2023-06-26', 'completed'),
(15, '2023-06-29', 'completed');

-- Order items (quantity + unit_price captured at time of sale)
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES
(1, 1, 2, 15.00), (1, 3, 1, 25.00),
(2, 4, 1, 90.00),
(3, 5, 1, 20.00), (3, 7, 2, 12.00),
(4, 2, 1, 55.00),
(5, 8, 1, 30.00),
(6, 1, 1, 15.00), (6, 6, 1, 120.00),
(7, 9, 1, 150.00),
(8, 3, 2, 25.00),
(9, 10, 1, 250.00),
(10, 4, 1, 90.00), (10, 1, 1, 15.00),
(11, 5, 2, 20.00),
(12, 6, 1, 120.00),
(13, 2, 1, 55.00), (13, 3, 1, 25.00),
(14, 9, 1, 150.00),
(15, 7, 3, 12.00),
(16, 8, 2, 30.00),
(17, 1, 1, 15.00),
(18, 10, 1, 250.00),
(19, 4, 1, 90.00),
(20, 5, 1, 20.00), (20, 7, 1, 12.00),
(21, 2, 1, 55.00),
(22, 6, 1, 120.00), (22, 1, 2, 15.00),
(23, 9, 1, 150.00),
(24, 3, 1, 25.00),
(25, 8, 1, 30.00),
(26, 10, 1, 250.00),
(27, 4, 2, 90.00),
(28, 1, 3, 15.00),
(29, 5, 1, 20.00),
(30, 6, 1, 120.00),
(31, 2, 1, 55.00), (31, 8, 1, 30.00),
(32, 9, 1, 150.00),
(33, 7, 2, 12.00),
(34, 10, 1, 250.00),
(35, 3, 1, 25.00),
(36, 4, 1, 90.00),
(37, 1, 1, 15.00), (37, 2, 1, 55.00),
(38, 6, 1, 120.00),
(39, 5, 2, 20.00);

-- ------------------------------------------------------------
-- QUERIES + OUTPUT
-- ------------------------------------------------------------

-- 1. Revenue per order (CTE)
WITH order_totals AS (
    SELECT order_id, SUM(quantity * unit_price) AS order_revenue
    FROM order_items
    GROUP BY order_id
)
SELECT o.order_id, o.order_date, c.first_name, c.last_name, ot.order_revenue
FROM order_totals ot
JOIN orders o ON ot.order_id = o.order_id
JOIN customers c ON o.customer_id = c.customer_id
WHERE o.status = 'completed'
ORDER BY o.order_date;
/* Output:
order_id | order_date | first_name | last_name | order_revenue
---------+------------+------------+-----------+--------------
1        | 2023-01-08 | Nadia      | Amiri     | 55           
2        | 2023-01-15 | Yusuf      | Kanaan    | 90           
3        | 2023-01-20 | Mona       | Sharif    | 44           
4        | 2023-01-28 | Nadia      | Amiri     | 55           
5        | 2023-02-02 | Bilal      | Rahal     | 30           
6        | 2023-02-10 | Yusuf      | Kanaan    | 135          
7        | 2023-02-14 | Reem       | Haidar    | 150          
9        | 2023-02-25 | Mona       | Sharif    | 250          
10       | 2023-03-01 | Zainab     | Naser     | 105          
11       | 2023-03-05 | Bilal      | Rahal     | 40           
12       | 2023-03-09 | Karim      | Assaf     | 120          
13       | 2023-03-14 | Nadia      | Amiri     | 80           
14       | 2023-03-19 | Sara       | Boulos    | 150          
15       | 2023-03-23 | Reem       | Haidar    | 36           
16       | 2023-03-27 | Fadi       | Dabbas    | 60           
17       | 2023-04-01 | Tamer      | Fakhoury  | 15           
18       | 2023-04-04 | Layla      | Habib     | 250          
19       | 2023-04-08 | Yusuf      | Kanaan    | 90           
20       | 2023-04-12 | Hassan     | Jaber     | 32           
21       | 2023-04-16 | Zainab     | Naser     | 55           
23       | 2023-04-24 | Mona       | Sharif    | 150          
24       | 2023-04-28 | Karim      | Assaf     | 25           
25       | 2023-05-02 | Wael       | Sukkar    | 30           
26       | 2023-05-06 | Sara       | Boulos    | 250          
27       | 2023-05-10 | Nadia      | Amiri     | 180          
28       | 2023-05-14 | Rasha      | Hourani   | 45           
29       | 2023-05-18 | Bilal      | Rahal     | 20           
30       | 2023-05-22 | Fadi       | Dabbas    | 120          
31       | 2023-05-26 | Layla      | Habib     | 85           
32       | 2023-05-30 | Yusuf      | Kanaan    | 150          
33       | 2023-06-02 | Reem       | Haidar    | 24           
34       | 2023-06-06 | Hassan     | Jaber     | 250          
35       | 2023-06-10 | Tamer      | Fakhoury  | 25           
36       | 2023-06-14 | Dina       | Marouf    | 90           
37       | 2023-06-18 | Zainab     | Naser     | 70           
38       | 2023-06-22 | Wael       | Sukkar    | 120          
39       | 2023-06-26 | Mona       | Sharif    | 40           
(37 rows)
*/

-- 2. Monthly revenue (completed orders only)
WITH order_totals AS (
    SELECT o.order_id, o.order_date, SUM(oi.quantity * oi.unit_price) AS order_revenue
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.status = 'completed'
    GROUP BY o.order_id, o.order_date
)
SELECT DATE_TRUNC('month', order_date)::DATE AS month,
       SUM(order_revenue) AS monthly_revenue
FROM order_totals
GROUP BY month
ORDER BY month;
/* Output:
month      | monthly_revenue
-----------+----------------
2023-01-01 | 244            
2023-02-01 | 565            
2023-03-01 | 591            
2023-04-01 | 617            
2023-05-01 | 880            
2023-06-01 | 619            
(6 rows)
*/

-- 3. Month-over-month revenue growth (window function: LAG)
WITH monthly AS (
    SELECT DATE_TRUNC('month', o.order_date)::DATE AS month,
           SUM(oi.quantity * oi.unit_price) AS revenue
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.status = 'completed'
    GROUP BY month
)
SELECT month,
       revenue,
       LAG(revenue) OVER (ORDER BY month) AS prev_month_revenue,
       ROUND(
           100.0 * (revenue - LAG(revenue) OVER (ORDER BY month))
           / NULLIF(LAG(revenue) OVER (ORDER BY month), 0), 1
       ) AS pct_growth
FROM monthly
ORDER BY month;
/* Output:
month      | revenue | prev_month_revenue | pct_growth
-----------+---------+--------------------+-----------
2023-01-01 | 244     | NULL               | NULL      
2023-02-01 | 565     | 244                | 131.60    
2023-03-01 | 591     | 565                | 4.60      
2023-04-01 | 617     | 591                | 4.40      
2023-05-01 | 880     | 617                | 42.60     
2023-06-01 | 619     | 880                | -29.70    
(6 rows)
*/

-- 4. Running total of revenue over time (window function: SUM OVER)
WITH monthly AS (
    SELECT DATE_TRUNC('month', o.order_date)::DATE AS month,
           SUM(oi.quantity * oi.unit_price) AS revenue
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.status = 'completed'
    GROUP BY month
)
SELECT month,
       revenue,
       SUM(revenue) OVER (ORDER BY month) AS running_total
FROM monthly
ORDER BY month;
/* Output:
month      | revenue | running_total
-----------+---------+--------------
2023-01-01 | 244     | 244          
2023-02-01 | 565     | 809          
2023-03-01 | 591     | 1400         
2023-04-01 | 617     | 2017         
2023-05-01 | 880     | 2897         
2023-06-01 | 619     | 3516         
(6 rows)
*/

-- 5. Top 3 products by revenue in each category (window function: RANK)
WITH product_revenue AS (
    SELECT p.category, p.product_name, SUM(oi.quantity * oi.unit_price) AS revenue
    FROM order_items oi
    JOIN products p ON oi.product_id = p.product_id
    GROUP BY p.category, p.product_name
),
ranked AS (
    SELECT *,
           RANK() OVER (PARTITION BY category ORDER BY revenue DESC) AS category_rank
    FROM product_revenue
)
SELECT category, product_name, revenue, category_rank
FROM ranked
WHERE category_rank <= 3
ORDER BY category, category_rank;
/* Output:
category    | product_name            | revenue | category_rank
------------+-------------------------+---------+--------------
Electronics | Noise-Cancel Headphones | 540     | 1            
Electronics | Mechanical Keyboard     | 275     | 2            
Electronics | Wireless Mouse          | 165     | 3            
Fitness     | Adjustable Dumbbells    | 600     | 1            
Fitness     | Yoga Mat                | 140     | 2            
Fitness     | Water Bottle            | 96      | 3            
Home        | Standing Desk           | 1000    | 1            
Home        | Office Chair            | 600     | 2            
Home        | Desk Lamp               | 150     | 3            
(9 rows)
*/

-- 6. Rank customers by total spend (window function: DENSE_RANK)
WITH customer_spend AS (
    SELECT c.customer_id, c.first_name, c.last_name, SUM(oi.quantity * oi.unit_price) AS total_spend
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.status = 'completed'
    GROUP BY c.customer_id, c.first_name, c.last_name
)
SELECT *,
       DENSE_RANK() OVER (ORDER BY total_spend DESC) AS spend_rank
FROM customer_spend
ORDER BY spend_rank;
/* Output:
customer_id | first_name | last_name | total_spend | spend_rank
------------+------------+-----------+-------------+-----------
3           | Mona       | Sharif    | 484         | 1         
2           | Yusuf      | Kanaan    | 465         | 2         
9           | Sara       | Boulos    | 400         | 3         
1           | Nadia      | Amiri     | 370         | 4         
11          | Layla      | Habib     | 335         | 5         
12          | Hassan     | Jaber     | 282         | 6         
7           | Zainab     | Naser     | 230         | 7         
5           | Reem       | Haidar    | 210         | 8         
10          | Fadi       | Dabbas    | 180         | 9         
14          | Wael       | Sukkar    | 150         | 10        
8           | Karim      | Assaf     | 145         | 11        
4           | Bilal      | Rahal     | 90          | 12        
13          | Dina       | Marouf    | 90          | 12        
15          | Rasha      | Hourani   | 45          | 13        
6           | Tamer      | Fakhoury  | 40          | 14        
(15 rows)
*/

-- 7. Days between each customer's consecutive orders (window function: LAG on dates)
WITH customer_orders AS (
    SELECT customer_id, order_id, order_date,
           LAG(order_date) OVER (PARTITION BY customer_id ORDER BY order_date) AS prev_order_date
    FROM orders
    WHERE status = 'completed'
)
SELECT customer_id, order_id, order_date, prev_order_date,
       order_date - prev_order_date AS days_since_last_order
FROM customer_orders
WHERE prev_order_date IS NOT NULL
ORDER BY customer_id, order_date;
/* Output:
customer_id | order_id | order_date | prev_order_date | days_since_last_order
------------+----------+------------+-----------------+----------------------
1           | 4        | 2023-01-28 | 2023-01-08      | 0                    
1           | 13       | 2023-03-14 | 2023-01-28      | 0                    
1           | 27       | 2023-05-10 | 2023-03-14      | 0                    
2           | 6        | 2023-02-10 | 2023-01-15      | 0                    
2           | 19       | 2023-04-08 | 2023-02-10      | 0                    
2           | 32       | 2023-05-30 | 2023-04-08      | 0                    
3           | 9        | 2023-02-25 | 2023-01-20      | 0                    
3           | 23       | 2023-04-24 | 2023-02-25      | 0                    
3           | 39       | 2023-06-26 | 2023-04-24      | 0                    
4           | 11       | 2023-03-05 | 2023-02-02      | 0                    
4           | 29       | 2023-05-18 | 2023-03-05      | 0                    
5           | 15       | 2023-03-23 | 2023-02-14      | 0                    
5           | 33       | 2023-06-02 | 2023-03-23      | 0                    
6           | 35       | 2023-06-10 | 2023-04-01      | 0                    
7           | 21       | 2023-04-16 | 2023-03-01      | 0                    
7           | 37       | 2023-06-18 | 2023-04-16      | 0                    
8           | 24       | 2023-04-28 | 2023-03-09      | 0                    
9           | 26       | 2023-05-06 | 2023-03-19      | 0                    
10          | 30       | 2023-05-22 | 2023-03-27      | 0                    
11          | 31       | 2023-05-26 | 2023-04-04      | 0                    
12          | 34       | 2023-06-06 | 2023-04-12      | 0                    
14          | 38       | 2023-06-22 | 2023-05-02      | 0                    
15          | 40       | 2023-06-29 | 2023-05-14      | 0                    
(23 rows)
*/

-- 8. Each order's revenue vs. that customer's average order value (window function: AVG OVER)
WITH order_totals AS (
    SELECT o.order_id, o.customer_id, SUM(oi.quantity * oi.unit_price) AS order_revenue
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.status = 'completed'
    GROUP BY o.order_id, o.customer_id
)
SELECT order_id, customer_id, order_revenue,
       ROUND(AVG(order_revenue) OVER (PARTITION BY customer_id), 2) AS customer_avg_order,
       order_revenue - AVG(order_revenue) OVER (PARTITION BY customer_id) AS diff_from_avg
FROM order_totals
ORDER BY customer_id, order_id;
/* Output:
order_id | customer_id | order_revenue | customer_avg_order | diff_from_avg
---------+-------------+---------------+--------------------+--------------
1        | 1           | 55            | 92.50              | -37.50       
4        | 1           | 55            | 92.50              | -37.50       
13       | 1           | 80            | 92.50              | -12.50       
27       | 1           | 180           | 92.50              | 87.50        
2        | 2           | 90            | 116.25             | -26.25       
6        | 2           | 135           | 116.25             | 18.75        
19       | 2           | 90            | 116.25             | -26.25       
32       | 2           | 150           | 116.25             | 33.75        
3        | 3           | 44            | 121                | -77          
9        | 3           | 250           | 121                | 129          
23       | 3           | 150           | 121                | 29           
39       | 3           | 40            | 121                | -81          
5        | 4           | 30            | 30                 | 0            
11       | 4           | 40            | 30                 | 10           
29       | 4           | 20            | 30                 | -10          
7        | 5           | 150           | 70                 | 80           
15       | 5           | 36            | 70                 | -34          
33       | 5           | 24            | 70                 | -46          
17       | 6           | 15            | 20                 | -5           
35       | 6           | 25            | 20                 | 5            
10       | 7           | 105           | 76.67              | 28.33        
21       | 7           | 55            | 76.67              | -21.67       
37       | 7           | 70            | 76.67              | -6.67        
12       | 8           | 120           | 72.50              | 47.50        
24       | 8           | 25            | 72.50              | -47.50       
14       | 9           | 150           | 200                | -50          
26       | 9           | 250           | 200                | 50           
16       | 10          | 60            | 90                 | -30          
30       | 10          | 120           | 90                 | 30           
18       | 11          | 250           | 167.50             | 82.50        
31       | 11          | 85            | 167.50             | -82.50       
20       | 12          | 32            | 141                | -109         
34       | 12          | 250           | 141                | 109          
36       | 13          | 90            | 90                 | 0            
25       | 14          | 30            | 75                 | -45          
38       | 14          | 120           | 75                 | 45           
28       | 15          | 45            | 45                 | 0            
(37 rows)
*/

-- 9. New vs. returning customers per month (CTE + window function: ROW_NUMBER)
WITH first_orders AS (
    SELECT customer_id,
           MIN(order_date) AS first_order_date
    FROM orders
    WHERE status = 'completed'
    GROUP BY customer_id
),
monthly_orders AS (
    SELECT o.order_id, o.customer_id, o.order_date,
           DATE_TRUNC('month', o.order_date)::DATE AS order_month,
           DATE_TRUNC('month', f.first_order_date)::DATE AS first_month
    FROM orders o
    JOIN first_orders f ON o.customer_id = f.customer_id
    WHERE o.status = 'completed'
)
SELECT order_month,
       COUNT(*) FILTER (WHERE order_month = first_month) AS new_customer_orders,
       COUNT(*) FILTER (WHERE order_month > first_month) AS returning_customer_orders
FROM monthly_orders
GROUP BY order_month
ORDER BY order_month;
/* Output:
order_month | new_customer_orders | returning_customer_orders
------------+---------------------+--------------------------
2023-01-01  | 4                   | 0                        
2023-02-01  | 2                   | 2                        
2023-03-01  | 4                   | 3                        
2023-04-01  | 3                   | 4                        
2023-05-01  | 2                   | 6                        
2023-06-01  | 1                   | 7                        
(6 rows)
*/